### ISSUE TITLE
Readme is not up to date?

### ISSUE THREAD

**Issue by 1am** [hatchet-dev/hatchet-python-quickstart#13]
Hi,

I've wanted to try out the simple-examples following the readme but am stuch with the following error on`poetry run hatchet`:
```
poetry run hatchet
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/src-L3iBMsmH-py3.10/lib/python3.10/site-packages/hatchet_sdk/clients/admin.py", line 226, in put_workflow
    resp: WorkflowVersion = self.client.PutWorkflow(
  File "/home/user/.cache/pypoetry/virtualenvs/src-L3iBMsmH-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/.cache/pypoetry/virtualenvs/src-L3iBMsmH-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNAVAILABLE
  details = "DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name"
  debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name", grpc_status:14, created_time:"2024-09-27T18:03:21.105402918+02:00"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/tmp/hatchet-python-quickstart/simple-examples/src/main.py", line 19, in start
    worker.register_workflow(SimpleWorkflow())
  File "/home/user/.cache/pypoetry/virtualenvs/src-L3iBMsmH-py3.10/lib/python3.10/site-packages/hatchet_sdk/worker.py", line 427, in register_workflow
    self.client.admin.put_workflow(workflow.get_name(), workflow.get_create_opts())
  File "/home/user/.cache/pypoetry/virtualenvs/src-L3iBMsmH-py3.10/lib/python3.10/site-packages/hatchet_sdk/clients/admin.py", line 233, in put_workflow
    raise ValueError(f"Could not put workflow: {e}")
ValueError: Could not put workflow: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNAVAILABLE
  details = "DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name"
  debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name", grpc_status:14, created_time:"2024-09-27T18:03:21.105402918+02:00"}"
>
```

The steps to reproduce are:
1. In the main folder `docker compose up` - Hatchet starts ok, everything fine
2. `poetry install`
3. `poetry run hatchet` <- this fails

I've tried changing someENV variables but not sure where the`hatchet-engine`comes from.Since I'mrunning the script outside of compose it should be localhost:7077 (as in [env config](https://github.com/hatchet-dev/hatchet-python-quickstart/blob/main/docker-compose.yml#L58)) but it never changes. What am I doing wrong? :)

**Comment by grutt** [comment]
Hi @1am it looks like our automations are not keeping this repo in sync.

While we look into this, I'd recommend checking out examples in: https://github.com/hatchet-dev/hatchet-python
And running hatchet-lite locally: https://docs.hatchet.run/self-hosting/hatchet-lite

**Comment by 1am** [comment]
Thank you, will look there. Running full hatchet was easy for me and have it integrated in one project, just was looking into the quickstart examples because I wanted to do a quick test of some features.
