### ISSUE TITLE
Instructions for Local Version in simple-examples fails with dns error

### ISSUE THREAD

**Issue by marcbutler** [hatchet-dev/hatchet-python-quickstart#14]
Hi,

Following the instructions in the readme files in both the root and simple-examples folder results dns failure looking for `hatchet-engine`.

Failure environment:
 - Ubuntu 22.04
 - Python 3.10.12

Reproduction steps:
 - Run docker compose as instructed in the top level readme.
 - Generate API token.
 - Setup and run worker locally as per the readme in `simple-examples/`.
 - Worker fails to register (output below) due to dns failure looking up 'hatchet-engine`.

Work around:
 - Map hatchet-engine to 127.0.0.1 in `/etc/hosts`.
 - Remap hatchet engine ports for GRPC (diff below) in `/docker-compose.yml`.

Diagnosis:

Inferred hostname is being embedded in the token.  Additionally hatchet engine port not exposed to local system.

Diff:
```yaml
diff --git a/docker-compose.yml b/docker-compose.yml
index 89b5273..814b817 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -76,7 +76,7 @@ services:
       migration:
         condition: service_completed_successfully
     ports:
-      - "7077:7070"
+      - "7070:7070"
     environment:
       DATABASE_URL: "postgres://hatchet:hatchet@postgres:5432/hatchet"
       SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
```

Output:
```shell
$ poetry --verbose run hatchet
Using virtualenv: /home/marc/.cache/pypoetry/virtualenvs/src-448ucQXO-py3.10
Traceback (most recent call last):
  File "/home/marc/.cache/pypoetry/virtualenvs/src-448ucQXO-py3.10/lib/python3.10/site-packages/hatchet_sdk/clients/admin.py", line 226, in put_workflow
    resp: WorkflowVersion = self.client.PutWorkflow(
  File "/home/marc/.cache/pypoetry/virtualenvs/src-448ucQXO-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/marc/.cache/pypoetry/virtualenvs/src-448ucQXO-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-11-27T13:13:29.896285743+11:00", grpc_status:14, grpc_message:"DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/marc/hiroco/eval/hatchet-python-quickstart/simple-examples/src/main.py", line 19, in start
    worker.register_workflow(SimpleWorkflow())
  File "/home/marc/.cache/pypoetry/virtualenvs/src-448ucQXO-py3.10/lib/python3.10/site-packages/hatchet_sdk/worker.py", line 427, in register_workflow
    self.client.admin.put_workflow(workflow.get_name(), workflow.get_create_opts())
  File "/home/marc/.cache/pypoetry/virtualenvs/src-448ucQXO-py3.10/lib/python3.10/site-packages/hatchet_sdk/clients/admin.py", line 233, in put_workflow
    raise ValueError(f"Could not put workflow: {e}")
ValueError: Could not put workflow: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-11-27T13:13:29.896285743+11:00", grpc_status:14, grpc_message:"DNS resolution failed for hatchet-engine:7070: C-ares status is not ARES_SUCCESS qtype=A name=hatchet-engine is_balancer=0: Misformatted domain name"}"
```

**Comment by marcbutler** [comment]
I found the environment setting `HATCHET_CLIENT_HOST_PORT` can be used toverride the hostname and port value in the token.
